feat: create PlusCircle icon
blockful-io/external-resolver-dapp pull request #116
Opened 2024-07-25 20:28 UTC by eduramme

2024-07-29 21:01 UTC, FrancoAguzzi requested changes

2024-07-29 21:01 UTC, FrancoAguzzi commented on pages/domains/index.tsx
> +              <ConnectButton.Custom>
We are not anymore using ConnectButton, please search for ConnectWallet component or something like, we are using a button to connect Metamask only

2024-07-29 21:18 UTC, eduramme commented on components/01-atoms/DappHeader.tsx
> +  const currentRoute = router.pathname;
yup

2024-07-30 18:46 UTC, FrancoAguzzi commented on components/01-atoms/DappHeader.tsx
> +  const currentRoute = router.pathname;
Where you able to test it?

2024-07-30 21:42 UTC, eduramme commented on components/01-atoms/DappHeader.tsx
> +  const currentRoute = router.pathname;
@FrancoAguzzi Yes, I tested it

2024-07-31 13:53 UTC, FrancoAguzzi approved these changes

2024-07-31 13:54 UTC, FrancoAguzzi commented on components/01-atoms/DappHeader.tsx
> +  const currentRoute = router.pathname;
Perfect

2024-07-31 14:16 UTC, merged