Add banner to arbitrum sepolia testnet
blockful-io/external-resolver-dapp pull request #203
Opened 2024-10-02 21:50 UTC by guilhermebins

This enhancement adds the Arbitrum Sepolia testnet banner to be displayed when users are connected.

2024-10-03 17:29 UTC, pikonha commented
we really appreciate your contribution to this @guilhermebins ✨ 

although the issue mentions adding the banner for `arbitrum sepolia`, I'd advise relying on the [viem's chain definition](https://github.com/wevm/viem/blob/main/src/chains/definitions/arbitrumGoerli.ts) which included a `testnet` flag for each chain.

the condition would be like this then: 

```ts
 const isConnectedToTestnet = () => chain?.testnet;
```

2024-10-03 21:12 UTC, FrancoAguzzi requested changes

2024-10-03 21:12 UTC, FrancoAguzzi commented on components/01-atoms/DappHeader.tsx
> +                                     /*add other testnet chain.id here*/];
```suggestion
  const testnetChainIds: number[] = [sepolia.id, arbitrumSepolia.id];
```

2024-10-03 21:13 UTC, FrancoAguzzi commented on components/01-atoms/DappHeader.tsx
> +                                     /*add other testnet chain.id here*/];
Hey @guilhermebins!

One comment on this, can you address it?

2024-10-04 17:25 UTC, eduramme approved these changes

2024-10-04 17:31 UTC, FrancoAguzzi approved these changes

2024-10-04 17:32 UTC, FrancoAguzzi commented
@guilhermebins thank you, looks sharp 📐✨

2024-10-04 17:49 UTC, FrancoAguzzi commented
<img width="1624" alt="Captura de Tela 2024-10-04 às 14 48 49" src="https://github.com/user-attachments/assets/156beb75-14ce-4e71-a470-3407feb26ffb">

<img width="1624" alt="Captura de Tela 2024-10-04 às 14 48 39" src="https://github.com/user-attachments/assets/d9ec9c97-8ca5-47ad-aada-3fc242d01e8d">

2024-10-04 17:49 UTC, merged